Write code for TC11
lqthai07t3/ThaiLuu_FinalTestByTestCase pull request #10
Opened 2021-09-06 10:13 UTC by lqthai07t3

- Code for TC11.
- Run code and check.

2021-09-06 12:21 UTC, tanmle requested changes

2021-09-06 12:21 UTC, tanmle commented on src/main/java/pages/RegisterPage.java
> +    private final By lblErrorRegisterForm = By.cssSelector("div#content > p.error");
why dont you name these to some thing like 
```
lblRegisterFormError
lblPasswordEror
lblbPidError
```

2021-09-06 12:44 UTC, lqthai07t3 commented on src/main/java/pages/RegisterPage.java
> +    private final By lblErrorRegisterForm = By.cssSelector("div#content > p.error");
Yeah, thank you for your help. I have fixed it. Please check again :)

2021-09-06 12:49 UTC, tanmle approved these changes

2021-09-07 01:37 UTC, MinhQuan119 approved these changes

2021-09-07 01:37 UTC, merged