Write code for TC07
lqthai07t3/ThaiLuu_FinalTestByTestCase pull request #7
Opened 2021-09-01 09:13 UTC by lqthai07t3

- Add more code to define Register tab in BasePage class.
- Add RegisterPage class and define element in Register page.
- Add RegisterTest class and code for TC07.
- Run code and check.

2021-09-01 09:17 UTC, tanmle requested changes

2021-09-01 09:17 UTC, tanmle commented on src/test/java/tests/RegisterTests.java
> +        String newPassword = DataHelper.getRandomPassword(8);
again, you don't need to random password.

2021-09-01 09:28 UTC, lqthai07t3 commented on src/test/java/tests/RegisterTests.java
> +        String newPassword = DataHelper.getRandomPassword(8);
Random Email needed for TC always works. So, I keep it
Random password and random pid have been removed.
Please check again

2021-09-01 09:28 UTC, MinhQuan119 commented on src/main/java/pages/RegisterPage.java
> +    private By btnRegister = By.xpath("//input[@value='Register']");
Can this control catch by CSS selector?

2021-09-01 09:29 UTC, lqthai07t3 commented on src/main/java/pages/RegisterPage.java
> +    private By btnRegister = By.xpath("//input[@value='Register']");
Yeah, ofcouse.

2021-09-01 09:33 UTC, lqthai07t3 commented on src/main/java/pages/RegisterPage.java
> +    private By btnRegister = By.xpath("//input[@value='Register']");
I has fixed it. Please check again

2021-09-01 09:52 UTC, tanmle commented on src/main/java/pages/RegisterPage.java
> +    public String getContent(){ return getLblContent().getText(); }
what is content?

2021-09-01 10:03 UTC, lqthai07t3 commented on src/main/java/pages/RegisterPage.java
> +    public String getContent(){ return getLblContent().getText(); }
Please check again

2021-09-01 10:33 UTC, MinhQuan119 commented on src/main/java/pages/RegisterPage.java
> +    private By btnRegister = By.xpath("//input[@value='Register']");
It changed to By.cssSelector("p.form-actions>input").
I mean can you catch cssSelector with @value='Register'

2021-09-01 14:11 UTC, lqthai07t3 commented on src/main/java/pages/RegisterPage.java
> +    private By btnRegister = By.xpath("//input[@value='Register']");
Please check it again :)

2021-09-06 01:34 UTC, tanmle approved these changes

2021-09-06 01:44 UTC, MinhQuan119 approved these changes

2021-09-06 01:44 UTC, merged